# Generated by Django 5.0 on 2023-12-22 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=500)),
                ('yum_factor', models.IntegerField(help_text='Enter an integer between 1 and 5 (inclusive).', validators=[django.core.validators.MinValueValidator(1, message='Value must be greater than or equal to 1.'), django.core.validators.MaxValueValidator(5, message='Value must be less than or equal to 5.')])),
            ],
        ),
    ]
